### ISSUE TITLE
unable to install on mac for R version 3.1.

### ISSUE THREAD

**Issue by aditya1315** [merliseclyde/BAS#1]
When I try to install it from github using the command,

`devtools::install_github('merliseclyde/BAS')`

I get the follwing error

> make: gfortran-4.2: No such file or directory

what do I do for this? (I have gfortran 4.8 installed on my system)

**Comment by merliseclyde** [comment]
Which MAC OS X are you running?    Is it possible to use the current version of R (3.3.2 on your platform)

The discussion on http://stackoverflow.com/questions/23916219/os-x-package-installation-depends-on-gfortran-4-8 is very helpful on using different versions of fortran with R.

See the posts at the end

Check which fortran is specified in the file
/Library/Frameworks/R.framework/Resources/etc/Makeconf

you may need to set `F77 = gfortran-4.8`

I have used the recommendation to change the options using the ~/.R/Makevars

I have the lines
```
F77 = /usr/local/gfortran/bin/gfortran
FC = /usr/local/gfortran/bin/gfortran
```

in my Makeovers file to use with fortran installed from macports

**Comment by akashrajkn** [comment]
@aditya1315, If you do not want to change the Makeconf, you could try installing gfortran-4.2 (you can [download from this site](https://r.research.att.com/tools/))

**Comment by aditya1315** [comment]
@merliseclyde thank you, I was able to install the package
