### ISSUE TITLE
Using JZS gives error

### ISSUE THREAD

**Issue by lizzyhuang** [merliseclyde/BAS#13]
Error in BAS::bas.lm(kid_score ~ . , data = cognitive, prior = "JZS", modelprior = uniform()) : 
  INTEGER() can only be applied to a 'integer', not a 'NULL'

This doesn't seem to happen before. I tried adding argument "a=1" and "alpha=1" but the error still showed.

**Comment by merliseclyde** [comment]
Please try using the current version on GitHub (1.4.8) and report back with more details about your OS, etc as I am not able to reproduce the error on MAC OS X.

(For faster response, please provide a self-contained reproducible example)
