### ISSUE TITLE
What is the default number of iterations for 'MCMC' method

### ISSUE THREAD

**Issue by akashrajkn** [merliseclyde/BAS#2]
@merliseclyde, thank you for this package.

I have a question. In the docs, for the function **bas.lm**, it says, the default value for 

    `MCMC.iterations = n.models * 10` 

if not set by user. I was looking at the source for this function, [at this line](https://github.com/merliseclyde/BAS/blob/master/R/bas.R#L151), it assigns the value of n.models*2  if MCMC.iterations is not specified by the user. Can you please clarify this?

**Comment by akashrajkn** [comment]
I have created a pull request #3 for this.

**Comment by merliseclyde** [comment]
This is a case of code/documentation mismatch.  I have merged your change into the base code so the code is now in agreement with the documentation.

Thanks!
