### ISSUE TITLE
Weights not found when using formula object for bas.lm

### ISSUE THREAD

**Issue by Jennifer2010** [merliseclyde/BAS#39]
**Describe the bug**
coef() is unable to find the weights when using estimator "MPM"

**To Reproduce**

library(MASS)
library(BAS)

data(UScrime, package = "MASS")
UScrime[, -2] <- log(UScrime[, -2])

Crime_aic =step(lm(y~., data = UScrime),k=2, trace = FALSE)

formula(Crime_aic)

Crime_ZS <- bas.lm(formula(Crime_aic),
                   data = UScrime,
                   prior = "ZS-null",
                   modelprior = uniform())

coef(Crime_ZS, estimator = "MPM")

**Desktop (please complete the following information):**
 - OS:  macOS Sierra

**Comment by merliseclyde** [comment]
same as issue #56
