### ISSUE TITLE
Warning messages in bas.lm

### ISSUE THREAD

**Issue by christineymshen** [merliseclyde/BAS#44]
Noted the following warning message while using bas.lm. As discussed earlier today, you mentioned that potentially can ignore it.

> Warning message:In model.matrix.default(mt, mf, contrasts) :   non-list contrasts argument ignored

**Comment by merliseclyde** [comment]
Version 1.5.4 on GitHub now addresses this issue!  Let me know if you encounter the warning after installing the new version.
