### ISSUE TITLE
se.fit=TRUE does not work in the predict.basglm() function with newdata

### ISSUE THREAD

**Issue by marcossn79** [merliseclyde/BAS#48]
It leads to the following error:

Error in array(STATS, dims[perm]) : 
  'data' must be of a vector type, was 'NULL'
In addition: Warning message:
In max(cumDim[cumDim <= lstats]) :

**Comment by aagaardk** [comment]
I just started a New issue on this topic before I saw this was in the closed issues section. It is still an issue, as noted with a reproducible example in the open issue.
