### ISSUE TITLE
dropping the null model from Jeffrey's prior conflicts with include.always

### ISSUE THREAD

**Issue by rodemann** [merliseclyde/BAS#61]
Hi Merlise,

When specifying covariates to be always included and setting Jeffrey's prior as prior on the coefficients, bas.glm() tries to drop the null model, which is not there, since we always included specific covariates. 

**minimal reproducible example**

 `data(Pima.tr, package="MASS");
formula <- type ~1 + npreg + glu + bp + bmi + ped;
covariates <- ~1 + npreg;  
BAS::bas.glm(formula = formula,
              data = Pima.tr,
              family = binomial(), 
              laplace = FALSE, 
              betaprior = Jeffreys(),
              modelprior = uniform(),
              method = "BAS",
              include.always = covariates
              )
`

**Expected behavior**
I think you should check whether there is a null model to drop [here](https://github.com/merliseclyde/BAS/blob/cc1b1266c41e138fc74fca7dd1b9d3ddc892ca6d/R/bas_glm.R#L560) before trying to drop it.  

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - R Version 4.2

Thanks for the cool package! :)

**Comment by merliseclyde** [comment]
@rodemann thanks for posting the issue!   "should" be fixed in version 1.6.5 for bas.glm on GitHub, but let me know if anything else pops up
