### ISSUE TITLE
`bas.predict` error with a single covariate

### ISSUE THREAD

**Issue by AleCarminati** [merliseclyde/BAS#68]
**Describe the bug**
When you create a BAS linear model with a single covariate and then you try to predict new data (with `se.fit=T`) the function returns the following error:
`Error in array(STATS, dims[perm]) : 'dims' cannot be of length 0`

**To Reproduce**   
```R
data("Hald")
hald.gprior =  bas.lm(Y ~ X2, data=Hald, alpha=13, prior="g-prior")
predict(hald.gprior, newdata=Hald, estimator="BPM", se.fit=TRUE)
```

**Expected behavior**
The function should return the 95% intervals for the prediction of new data.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 
 - R Version: 4.1.2

**Comment by merliseclyde** [comment]
Dev version 1.6.5 passes current tests; closing issue for now.
